/*
 * author: Clément Levallois
 */
package net.clementlevallois.web.exports.plugin.controller;

import com.google.gson.JsonObject;


/**
 *
 * @author LEVALLOIS
 */
public class JPanelWebExport extends javax.swing.JPanel {

    JsonObject responsePublishingAction;

    /**
     * Creates new form JPanelWebExport
     */
    public JPanelWebExport() {
        initComponents();
        jLabelPromptCopyUrl.setVisible(false);
        jTextUrlPublishedNetwork.setVisible(false);
        jTextAreaErrorMessage.setVisible(false);
        jTextAreaErrorMessage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        tabNoGithub = new javax.swing.JPanel();
        tabGithub = new javax.swing.JPanel();
        jButtonGithubPublish = new javax.swing.JButton();
        jButtonGithubCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNoGithub = new javax.swing.JTextArea();
        jTextFieldNoGithubFilename = new javax.swing.JTextField();
        jLabelPromptChooseNetworkFilename = new javax.swing.JLabel();
        jTextUrlPublishedNetwork = new javax.swing.JTextField();
        jLabelPromptCopyUrl = new javax.swing.JLabel();
        jScrollPaneErrorMessage = new javax.swing.JScrollPane();
        jTextAreaErrorMessage = new javax.swing.JTextArea();

        javax.swing.GroupLayout tabNoGithubLayout = new javax.swing.GroupLayout(tabNoGithub);
        tabNoGithub.setLayout(tabNoGithubLayout);
        tabNoGithubLayout.setHorizontalGroup(
            tabNoGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        tabNoGithubLayout.setVerticalGroup(
            tabNoGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        tabs.addTab(org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.tabNoGithub.TabConstraints.tabTitle"), tabNoGithub); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonGithubPublish, org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jButtonGithubPublish.text")); // NOI18N
        jButtonGithubPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGithubPublishActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonGithubCancel, org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jButtonGithubCancel.text")); // NOI18N

        jTextAreaNoGithub.setEditable(false);
        jTextAreaNoGithub.setColumns(20);
        jTextAreaNoGithub.setLineWrap(true);
        jTextAreaNoGithub.setRows(5);
        jTextAreaNoGithub.setText(org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jTextAreaNoGithub.text")); // NOI18N
        jScrollPane1.setViewportView(jTextAreaNoGithub);

        jTextFieldNoGithubFilename.setText(org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jTextFieldNoGithubFilename.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPromptChooseNetworkFilename, org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jLabelPromptChooseNetworkFilename.text")); // NOI18N

        jTextUrlPublishedNetwork.setEditable(false);
        jTextUrlPublishedNetwork.setText(org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jTextUrlPublishedNetwork.text")); // NOI18N
        jTextUrlPublishedNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUrlPublishedNetworkActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPromptCopyUrl, org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.jLabelPromptCopyUrl.text")); // NOI18N

        jScrollPaneErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        jTextAreaErrorMessage.setColumns(20);
        jTextAreaErrorMessage.setForeground(new java.awt.Color(255, 51, 51));
        jTextAreaErrorMessage.setRows(3);
        jScrollPaneErrorMessage.setViewportView(jTextAreaErrorMessage);

        javax.swing.GroupLayout tabGithubLayout = new javax.swing.GroupLayout(tabGithub);
        tabGithub.setLayout(tabGithubLayout);
        tabGithubLayout.setHorizontalGroup(
            tabGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabGithubLayout.createSequentialGroup()
                .addComponent(jTextUrlPublishedNetwork)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabGithubLayout.createSequentialGroup()
                .addGroup(tabGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabGithubLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonGithubPublish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGithubCancel))
                    .addGroup(tabGithubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPromptChooseNetworkFilename)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNoGithubFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabGithubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(44, 44, 44))
            .addGroup(tabGithubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneErrorMessage)
                .addContainerGap())
            .addGroup(tabGithubLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabelPromptCopyUrl)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        tabGithubLayout.setVerticalGroup(
            tabGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabGithubLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNoGithubFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPromptChooseNetworkFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(tabGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGithubPublish)
                    .addComponent(jButtonGithubCancel))
                .addGap(18, 18, 18)
                .addComponent(jLabelPromptCopyUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jTextUrlPublishedNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab(org.openide.util.NbBundle.getMessage(JPanelWebExport.class, "JPanelWebExport.tabGithub.TabConstraints.tabTitle"), tabGithub); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGithubPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGithubPublishActionPerformed
        String filename = jTextFieldNoGithubFilename.getText();
        responsePublishingAction = PublishingActions.publishToRetinaViaNocodeFunctions(filename);
        if (responsePublishingAction.has("200")) {
            String urlPublishedGraph = "https://ouestware.gitlab.io/retina/beta/#/graph/?url=" + "https://test.nocodefunctions.com/gephi-viewer/published/" + filename;
            jTextUrlPublishedNetwork.setText(urlPublishedGraph);
            jTextUrlPublishedNetwork.setVisible(true);
            jLabelPromptCopyUrl.setVisible(true);
        } else if (!responsePublishingAction.keySet().isEmpty()) {
            jTextAreaErrorMessage.setVisible(true);
            jTextAreaErrorMessage.setText(responsePublishingAction.get(responsePublishingAction.keySet().iterator().next()).getAsString());
        }
    }//GEN-LAST:event_jButtonGithubPublishActionPerformed

    private void jTextUrlPublishedNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUrlPublishedNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUrlPublishedNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGithubCancel;
    private javax.swing.JButton jButtonGithubPublish;
    private javax.swing.JLabel jLabelPromptChooseNetworkFilename;
    private javax.swing.JLabel jLabelPromptCopyUrl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneErrorMessage;
    private javax.swing.JTextArea jTextAreaErrorMessage;
    private javax.swing.JTextArea jTextAreaNoGithub;
    private javax.swing.JTextField jTextFieldNoGithubFilename;
    private javax.swing.JTextField jTextUrlPublishedNetwork;
    private javax.swing.JPanel tabGithub;
    private javax.swing.JPanel tabNoGithub;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
